### ISSUE TITLE
ACL Anthology RSS: Add a directory for blog posts and announcements

### ISSUE THREAD

**Issue by CSchoel** [CSchoel/acl-anthology#3]
## Description

Apart from an RSS feed, https://github.com/acl-org/acl-anthology/issues/358 also mentions a directory for blog posts:

> A /posts/ directory where we can place new blog posts and announcements (we're open to naming suggestions).

## Questions

Are there any specific requirements for what those blog posts should look like? I guess Hugo has some kind of standard blogging support. Does that suffice?

## DoD

- [x] Research blogging support in Hugo.
- [x] Add everything that is required to support blogs and announcements.
- [x] Write first announcement for this feature as a test.
- [x] Add posts in the new directory to the RSS feed created in #2.
- [x] Run a local web server with Hugo and check that everything looks good.

**Comment by mbollmann** [comment]
We already have a few "info" pages whose templates already look quite blog-post-ish, e.g. https://aclanthology.org/info/development/

What's necessary is mainly to make a new folder with markdown sources for blog posts, make hugo aware of the folder and which template it should use, and maybe clone the template we currently use for info pages for this purpose, so that it can be customized separately.

**Comment by CSchoel** [comment]
I added a new top-level content folder called `news` and copied the layout for the `info` pages, as suggested. I also added a link to the RSS feed for that new folder to the text that links to the mailing list. To test that everything works, I created a post announcing the new RSS feeds and the news section. Feel free to use or ignore that text however you like. :smile: 

One question: Is there a reason why the existing [`posts` folder](https://aclanthology.org/posts/) should not be used for this? If not, I can roll back my changes and link to that one instead.
